name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node LTS
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build

      - name: Generate release
        run: pnpx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Publish to NPM
        run: npm publish --provenance --access public --no-git-checks
